<?php
/**
 * Created by PhpStorm.
 * User: yannick
 * Date: 30/07/19
 * Time: 23:46
 */
namespace Test\Banner\Block\Adminhtml;

class BannerList extends \Magento\Backend\Block\Widget\Grid\Container
{
    protected function _prepareLayout()
    {
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
}